stages:
  - build
  
build:
  stage: build
  script:
    - mkdir ./build
    - cmake -DENABLE_CPACK=ON  -DBUILD_QTAPPS=OFF
    - make -j2 -l2
    - make DESTDIR=./build install
    - make DESTDIR=./build package
    - scp nsxtool*.deb gitlabci-nsxtool@halltestvm:/mnt/data/software/nsxtool/uploads

  only:
    - master
  tags:
    - ubuntu14.04