windows-msvc:
  script:
    - mkdir build
    - cd build
    - cmake --version
    - set BOOST_ROOT=c:\local\boost_1_61_0
    - set BOOST_LIBRARYDIR=c:\local\boost_1_61_0\lib64-msvc-14.0
    - set EIGEN3_INCLUDE_DIR=C:\Users\ci\Libraries\eigen
    - set PATH=C:\Users\ci\Libraries\eigen;%PATH%
    - dir C:\Users\ci\Libraries\eigen
    - cmake .. -G"Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release
  tags:
    - windows

#linux:
#  script:
#    - mkdir ./build
#    - cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_CPACK=OFF -DBUILD_QTAPPS=OFF -DCMAKE_INSTALL_PREFIX=./build
#    - make -j2 -l2
#    - make install
#    - ctest -j2 -l2
#    - rm CMakeCache.txt
#    - cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_CPACK=ON -DBUILD_QTAPPS=ON -DCMAKE_PREFIX_PATH=/opt/qt57
#    - make package
#  artifacts:
#    paths:
#    - nsxtool*deb
#  only:
#    - master
#    - develop
#  tags:
#    - ubuntu14.04

#mac:
#  script:
#    - mkdir ./build
#    - cd build
#    - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_QTAPPS=OFF -DCMAKE_INSTALL_PREFIX=. ..
#    - make -j4 -l4
#    - make install
#    - ctest -j4 -l4
#    - rm CMakeCache.txt
#    - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_QTAPPS=ON -DCMAKE_INSTALL_PREFIX=. -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.6.0/ ..
#    - make -j4 -l4
#    - make install
#    - declare -x CPLUS_INCLUDE_PATH=/usr/local/include:/usr/local/opt/eigen/include/eigen3:/usr/local/opt/boost/include:${CI_PROJECT_DIR}/build/include/NSXTool
#    - declare -x LIBRARY_PATH=${CI_PROJECT_DIR}/build/nsxlib:/usr/local/opt/boost/lib/:/usr/local/opt/fftw/lib/
#    - mkdir qmake-build
#    - cd qmake-build
#    - /usr/local/opt/qt5/bin/qmake ${CI_PROJECT_DIR}/build/apps/NSXQt/NSXQt.pro CONFIG+=release
#    - make -j4 -l4
#    - /usr/local/opt/qt5/bin/macdeployqt nsxtool.app/ -dmg
#  artifacts:
#    paths:
#    - ${CI_PROJECT_DIR}/build/qmake-build/nsxtool*dmg
#  only:
#    - master
#    - develop
#  tags:
#    - mac

