stages:
  - build
  
build:
  stage: build
  script:
    - mkdir ./build
    - cmake -DENABLE_CPACK=ON  -DBUILD_QTAPPS=ON -DCMAKE_INSTALL_PREFIX=./build
    - make -j2 -l2
    - make install
    - ctest -j2 -l2
    - make package
    - scp nsxtool*.deb gitlabci-nsxtool@nsxtool.ill.fr:/mnt/data/software/nsxtool/uploads

  only:
    - master
  tags:
    - ubuntu14.04