linux:
  script:
    - mkdir ./build
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./build
    - make -j2 -l2
    - make install
    - ctest -j2 -l2
    - rm CMakeCache.txt
    - cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_CPACK=ON -DBUILD_QTAPPS=ON
    - make package
  artifacts:
    paths:
    - nsxtool*deb
  only:
    - master
  tags:
    - ubuntu14.04

mac:
  script:
    - mkdir ./build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=.
    - make -j4 -l4
    - make install
    - ctest -j4 -l4
    - rm CMakeCache.txt
    - cmake -DCMAKE_BUILD_TYPE=Release
    - make -j4 -l4
    - make install
    - declare -x CPLUS_INCLUDE_PATH=/usr/local/opt/eigen/include/eigen3:/usr/local/opt/boost/include:${CI_PROJECT_DIR}/build/include/NSXTool
    - declare -x LIBRARY_PATH=${CI_PROJECT_DIR}/build/lib:/usr/local/opt/boost/lib/:/usr/local/opt/fftw/lib/
    - cd ${CI_PROJECT_DIR}/apps/NSXQt/
    - /usr/local/opt/qt5/bin/qmake CONFIG+=release
    - make -j4 -l4
    - /usr/local/opt/qt5/bin/macdeployqt nsxtool.app/ -dmg
  artifacts:
    paths:
    - nsxtool*dmg
  only:
    - master
  tags:
    - mac

