linux:
  script:
    - mkdir ./build
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./build
    - make -j2 -l2
    - make install
    - ctest -j2 -l2
    - rm CMakeCache.txt
    - cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_CPACK=ON -DBUILD_QTAPPS=ON
    - make package
    - scp nsxtool*.deb gitlabci-nsxtool@nsxtool.ill.fr:/mnt/data/software/nsxtool/uploads

  only:
    - master
  tags:
    - ubuntu14.04

#mac:
#  script:
#    - mkdir ./build
#    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./build
#    - make -j4 -l4
#    - make install
#    - ctest -j4 -l4
#    - rm CMakeCache.txt
#  only:
#    - master
#  tags:
#    - mac

