stages:
  - ci
  - deploy

# trusty pipeline

ci:trusty:
  stage: ci
  script:
    - echo "ubuntu ci"
    - ./build_server/debian/run_build.sh
    - ./build_server/debian/run_tests.sh
  allow_failure: false
  only:
    - /^bugfix/.*$/
    - /^feature/.*$/
    - /^refactoring/.*$/
  tags:
    - ubuntu14.04

deploy:trusty:
  stage: deploy
  script:
    - ./build_server/debian/run_build.sh
    - ./build_server/debian/run_tests.sh
    - ./build_server/debian/run_deploy.sh
  allow_failure: false
  only:
    - triggers
    - tags
    - /^release/.*$/
    - /^hotfix/.*$/
    - develop
  artifacts:
    paths:
    - ${CI_PROJECT_DIR}/build/nsxtool*deb
  tags:
    - ubuntu14.04

# osx pipeline

ci:osx:
  stage: ci
  script:
    - echo "osx ci"
    - ./build_server/osx/run_build.sh
    - ./build_server/osx/run_tests.sh
  allow_failure: false
  only:
    - /^bugfix/.*$/
    - /^feature/.*$/
    - /^refactoring/.*$/
  tags:
    - macmini2

deploy:osx:
  stage: deploy
  script:
    - ./build_server/osx/run_build.sh
    - ./build_server/osx/run_tests.sh
    - ./build_server/osx/run_deploy.sh
  allow_failure: false
  only:
    - triggers
    - tags
    - /^release/.*$/
    - /^hotfix/.*$/
    - develop
  artifacts:
    paths:
    - ${CI_PROJECT_DIR}/build/qmake-build/nsxtool*dmg
  tags:
    - macmini2

# windows pipeline

ci:windows:
  stage: ci
  script:
    - cmd /k .\build_server\windows\run_build.bat
    - cmd /k .\build_server\windows\run_tests.bat
  allow_failure: false
  only:
    - /^bugfix/.*$/
    - /^feature/.*$/
    - /^refactoring/.*$/
  tags:
    - windows

deploy:windows:
  stage: deploy
  script:
    - cmd /k .\\build_server\\windows\\run_build.bat
    - cmd /k .\\build_server\\windows\\run_tests.bat
    - cmd /k .\\build_server\\windows\\run_deploy.bat
  allow_failure: false
  only:
    - triggers
    - tags
    - /^release/.*$/
    - /^hotfix/.*$/
    - develop
  artifacts:
    paths:
    - \%CI_PROJECT_DIR\%\\build\\nsxtool*.exe
  tags:
    - windows

